import modules
import math
import datetime
print(modules.add(3,4))
print(modules.les(5,2))
print(modules.multi(8,8))
print(modules.divid(8,2))
print(min(1,2,3,4,5,56))
print(max(11,22,33,44,55,))
print(abs(-5))
print(pow(4,3))
print(math.pi)
print(math.sqrt(7))
print(math.factorial(5))
print(math.ceil(2.5))
print(math.floor(3.8))
x=datetime.datetime.now()
print(x)
print(x.strftime("%A"))
print(x.strftime("%a"))
print(x.strftime("%B"))
print(x.strftime("%b"))
print(x.strftime("%Y"))
print(x.strftime("%y"))
print(x.strftime("%H"))
print(x.strftime("%I"))