
import os
#a=open("file1.txt","x")
b=open("file1.txt","w")
b.write("my name is shamil\niam from malappuram\niam 21 years old")
b.close()
c=open("file1.txt","r")
print(c.read())
c.close()
c=open("file1.txt","r")
print(c.read(10))
c.close()
c=open("file1.txt","r")
print(c.readline())
print(c.readline())
c.close()
d=open("file1.txt","a")
d.write("\niam a student")
d.close()
e=open("file1.txt","w")
e.write("how are you")
e.close()
#f=open("file2.txt","x")
#os.remove("file2.txt")
os.rmdir("newfolder")