#a=open("shamil.txt","x")
b=open("shamil.txt","w")
b.write("hai\nhow are you\nwhat you want")
b.close()
c=open("shamil.txt","r")
print(c.read(22))
c.close()
d=open("shamil.txt","a")
d.write('\nwhat can i do for you')
d.close()
e=open("shamil.txt","r")
print(e.read())
e.close()
#h=open("cat.txt","x")
import os
os.remove("cat.txt")